# Travis build file for checking for errors.

sudo: false

before_install:
- git clone https://github.com/eurocris/CERIF-TG-Tools.git ../CERIF-TG-Tools

language: java

jdk:
    - openjdk8

install: true

script:
    - travis_wait ./tools/compile.sh
